USE [Bookingdb]
CREATE TABLE [dbo].[User](
	[User_ID] [int] IDENTITY(1,1) NOT NULL,
	[First_Name] [nvarchar](50) NOT NULL,
	[Last_Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Phone] [nchar](10) NOT NULL,
	[Address] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Role] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE Camera
(   CAMERA_ID INT IDENTITY(1,1) PRIMARY KEY,
  ETAJ INT,
  NR_CAMERA INT,
  NR_DORMITOARE INT,
  PRET FLOAT,
)

ALTER TABLE Camera 
ADD FOREIGN KEY (ID_DOTARI) REFERENCES Dotari(DOTARI_ID);

Create TABLE Dotari
(DOTARI_ID INT IDENTITY(1,1) PRIMARY KEY
)
Create TABLE Servicii
(Serivicii_ID INT IDENTITY(1,1) PRIMARY KEY,
  CAMERA_ID int FOREIGN KEY REFERENCES Camera(CAMERA_ID),
  ServiciiString varchar(100)

)
ALTER TABLE Camera
DROP COLUMN  ID_DOTARI;

delete FROM CAMERA 
alter table CAMERA add constraint pinky unique(NR_CAMERA);
alter table [dbo].[User] add constraint pink unique(Email);



ALTER TABLE Servicii
ADD FOREIGN KEY (CAMERA_ID) REFERENCES Camera(CAMERA_ID);
ALTER TABLE Facilitati
ADD StringFacilitati

CREATE PROCEDURE SelectServicii @ID_CAMERA INT
AS
SELECT * FROM Servicii WHERE CAMERA_ID = @ID_CAMERA

EXEC SelectServicii @ID_CAMERA = 20;

CREATE PROCEDURE GetServicii @NR_CAMERA INT
AS
SELECT ServiciiString FROM Servicii WHERE CAMERA_ID = @NR_CAMERA
CREATE PROCEDURE GETID_CAMERA @NR_CAMERA INT
AS
SELECT CAMERA_ID FROM Camera WHERE NR_CAMERA=@NR_CAMERA
DROP PROCEDURE GetServicii

delete Servicii

Alter table Camera Add DELETED bit

CREATE PROCEDURE DELETEROOM @ID_CAMERA INT
AS
UPDATE Camera
SET Camera.DELETED= 1
WHERE CAMERA_ID = @ID_CAMERA

CREATE PROCEDURE ORDERBYPRICE AS
SELECT * FROM Camera ORDER BY PRET

CREATE TABLE CLIENTI(CLIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID int FOREIGN KEY REFERENCES [dbo].[USER](USER_ID),
  ID_REZERVARI int
)
INSERT INTO CLIENTI(USER_ID)
SELECT User_ID FROM [dbo].[User]
WHERE Role= 'Customer'

CREATE PROCEDURE UPDATEROOM @ID_CAMERA INT,@BALCON bit,@ETAJ int,@NR_Dormitoare INT,@PRET float,@BUCATARIE bit,@FRIGIDER bit
AS
UPDATE Camera
SET BALCON= @BALCON,
ETAJ=@ETAJ,
NR_DORMITOARE=@NR_Dormitoare,
PRET=@PRET,
BUCATARIE=@BUCATARIE,
FRIGIDER=@FRIGIDER
WHERE CAMERA_ID = @ID_CAMERA

CREATE PROCEDURE UPDATESERVICII @ID_CAMERA INT,@SERVICII varchar(100)
AS 
UPDATE Servicii
SET ServiciiString=@SERVICII
WHERE CAMERA_ID=@ID_CAMERA

INSERT INTO SERVICII(CAMERA_ID)
SELECT CAMERA_ID FROM Camera

ALTER TABLE [dbo].[User] 
add DELETED BIT

CREATE PROCEDURE DELETEUSER @ID_USER INT
AS
UPDATE [dbo].[User]
SET [dbo].[User].DELETED= 1
WHERE User_ID = @ID_USER

CREATE PROCEDURE GetUserIdByMail @Mail varchar(50)
AS
SELECT User_ID FROM [dbo].[User] WHERE Email=@Mail
