//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camera()
        {
            this.Serviciis = new HashSet<Servicii>();
        }
    
        public int CAMERA_ID { get; set; }
        public Nullable<int> ETAJ { get; set; }
        public Nullable<int> NR_CAMERA { get; set; }
        public Nullable<int> NR_DORMITOARE { get; set; }
        public Nullable<double> PRET { get; set; }
        public Nullable<bool> BALCON { get; set; }
        public Nullable<bool> BUCATARIE { get; set; }
        public Nullable<bool> FRIGIDER { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicii> Serviciis { get; set; }
    }
}
