//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTI
    {
        public int CLIENT_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> ID_REZERVARI { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual User User { get; set; }
    }
}
