//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Bookingdb : DbContext
    {
        public Bookingdb()
            : base("name=Bookingdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camera> Cameras { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CLIENTI> CLIENTIs { get; set; }
        public virtual DbSet<Servicii> Serviciis { get; set; }
    
        public virtual int DELETEROOM(Nullable<int> iD_CAMERA)
        {
            var iD_CAMERAParameter = iD_CAMERA.HasValue ?
                new ObjectParameter("ID_CAMERA", iD_CAMERA) :
                new ObjectParameter("ID_CAMERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEROOM", iD_CAMERAParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> GetBalcon(Nullable<int> numar_Camera)
        {
            var numar_CameraParameter = numar_Camera.HasValue ?
                new ObjectParameter("Numar_Camera", numar_Camera) :
                new ObjectParameter("Numar_Camera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("GetBalcon", numar_CameraParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GETID_CAMERA(Nullable<int> nR_CAMERA)
        {
            var nR_CAMERAParameter = nR_CAMERA.HasValue ?
                new ObjectParameter("NR_CAMERA", nR_CAMERA) :
                new ObjectParameter("NR_CAMERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GETID_CAMERA", nR_CAMERAParameter);
        }
    
        public virtual ObjectResult<string> GetServicii(Nullable<int> nR_CAMERA)
        {
            var nR_CAMERAParameter = nR_CAMERA.HasValue ?
                new ObjectParameter("NR_CAMERA", nR_CAMERA) :
                new ObjectParameter("NR_CAMERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetServicii", nR_CAMERAParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> SelectAllProperties(Nullable<int> numar_Camera)
        {
            var numar_CameraParameter = numar_Camera.HasValue ?
                new ObjectParameter("Numar_Camera", numar_Camera) :
                new ObjectParameter("Numar_Camera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("SelectAllProperties", numar_CameraParameter);
        }
    
        public virtual ObjectResult<SelectServicii_Result> SelectServicii(Nullable<int> iD_CAMERA)
        {
            var iD_CAMERAParameter = iD_CAMERA.HasValue ?
                new ObjectParameter("ID_CAMERA", iD_CAMERA) :
                new ObjectParameter("ID_CAMERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectServicii_Result>("SelectServicii", iD_CAMERAParameter);
        }
    }
}
