//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTE
    {
        public int OFERTE_ID { get; set; }
        public Nullable<int> REDUCERE { get; set; }
        public string NUME_OFERTA { get; set; }
        public string DATA_INCEPERE { get; set; }
        public string DATA_FINAL { get; set; }
    }
}
